config:
  shellVerbosity: 0
  dbDriver: mysql
  dbHost: shlink-mysql
  defaultDomain: "sl.example.com"
  isHttpsEnabled: true
  anonymizeRemoteAddr: true
  # if set to true, but want precise geolocation data, set anonymousRemoteAddr to false
  skipInitialGeoliteDownload: false
  # redisServers: shlink-redis
  # redisPubSubEnabled: true
  cacheNamespace: shlink
  disableIpTracking: false
  disableTracking: false
kubernetesClusterDomain: cluster.local
secret:
  dbUser: shlink
  dbPassword: shlink
  geoliteLicenseKey: ""
  initialApiKey: ""
server:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
persistence: 
  storageClass: ""
shlink:
  revisionHistoryLimit: 5
  shlinkServer:
    image:
      repository: shlinkio/shlink
      tag: "4.1"
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
webClient:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  shlinkWebClient:
    image:
      repository: shlinkio/shlink-web-client
      tag: "4.1"
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  type: ClusterIP
