config:
  shellVerbosity: 0
  dbDriver: mysql
  dbHost: shlink-mysql
  defaultDomain: "sl.example.com"
  isHttpsEnabled: true
  anonymizeRemoteAddr: true
  skipInitialGeoliteDownload: false
  redisServers: shlink-redis
  redisPubSubEnabled: true
  cacheNamespace: shlink
  disableIpTracking: false
  disableTracking: false
kubernetesClusterDomain: cluster.local
secret:
  dbUser: shlink
  dbPassword: shlink
  geoliteLicenseKey: ""
  initialApiKey: ""
server:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
persistence: 
  storageClass: ""
shlink:
  revisionHistoryLimit: 5
  shlinkServer:
    image:
      repository: shlinkio/shlink
      tag: "4.1"
    resources:
      requests:
        cpu: 200m
    hpa:
      enabled: true
    vpa:
      enabled: false
webClient:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  shlinkWebClient:
    image:
      repository: shlinkio/shlink-web-client
      tag: "4.1"
  type: ClusterIP
