apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink.fullname" . }}-server
  labels:
    app: shlink-server
  {{- include "shlink.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.shlink.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: shlink-server
    {{- include "shlink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: shlink-server
      {{- include "shlink.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "shlink.fullname" . }}-config
        - secretRef:
            name: {{ include "shlink.fullname" . }}-secret
        image: {{ .Values.shlink.shlinkServer.image.repository }}:{{ .Values.shlink.shlinkServer.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /rest/health
            port: http
          timeoutSeconds: 10
        name: shlink-server
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /rest/health
            port: http
          timeoutSeconds: 2
        {{- if .Values.shlink.shlinkServer.resources }}
        resources: {{- toYaml .Values.shlink.shlinkServer.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/shlink/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "shlink.fullname" . }}-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink.fullname" . }}-web-client
  labels:
    app: shlink-web-client
  {{- include "shlink.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shlink-web-client
    {{- include "shlink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: shlink-web-client
      {{- include "shlink.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.webClient.shlinkWebClient.image.repository }}:{{ .Values.webClient.shlinkWebClient.image.tag | default .Chart.AppVersion }}
        name: shlink-web-client
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- if .Values.webClient.shlinkWebClient.resources }}
        resources: {{- toYaml .Values.webClient.shlinkWebClient.resources | nindent 10 }}
        {{- end }}