apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shlink.fullname" . }}-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ required "persistence.storageClass is required" .Values.persistence.storageClass }}