apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shlink.fullname" . }}-secret
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
stringData:
  DB_USER: {{ required "secret.dbUser is required" .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ required "secret.dbPassword is required" .Values.secret.dbPassword | quote }}
  GEOLITE_LICENSE_KEY: {{ required "secret.geoliteLicenseKey is required" .Values.secret.geoliteLicenseKey | quote }}
  INITIAL_API_KEY: {{ required "secret.initialApiKey is required" .Values.secret.initialApiKey | quote }}
type: Opaque