apiVersion: v1
kind: Service
metadata:
  name: {{ include "shlink.fullname" . }}-server
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  selector:
    app: shlink-server
  {{- include "shlink.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 }}
---
{{- if .Values.shlink.shlinkServer.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "shlink.fullname" . }}-server
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shlink-server
{{- end }}
---
{{- if .Values.shlink.shlinkServer.vpa.enabled }}
kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: {{ include "shlink.fullname" . }}-server
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       "shlink-server"
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        memory: "128Mi"
      maxAllowed:
        memory: "512Mi"
      controlledResources: ["memory"]
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shlink.fullname" . }}-server
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  rules:
  - host: sl.coderstrust.global
    http:
      paths:
      - backend:
          service:
            name: '{{ include "shlink.fullname" . }}-server'
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - sl.coderstrust.global
    secretName: sl-tls